#!/usr/bin/env python3
"""
分层抽象可视化系统 - 完整实现示例
演示三层架构如何协同工作
"""

import asyncio
import json
import math
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from datetime import datetime


# ============== 第一层：原子渲染层（底层）==============

class AtomicRenderer:
    """
    原子渲染层：只渲染基本图形，不包含任何业务逻辑
    特点：100%确定性、纯函数、无副作用、完全安全
    """
    
    # 支持的原子元素类型（白名单）
    SUPPORTED_ELEMENTS = {
        "circle", "ellipse", "rectangle", "line", 
        "arrow", "text", "polygon"
    }
    
    # 支持的颜色格式（白名单）
    COLOR_PATTERN = re.compile(r'^#[0-9A-Fa-f]{6}$')
    
    # 范围限制
    COORDINATE_RANGE = {"x": (0, 2000), "y": (0, 2000)}
    SIZE_RANGE = {"radius": (0.1, 1000), "width": (0.1, 2000), "height": (0.1, 2000)}
    
    def render(self, composition: Dict) -> str:
        """渲染组合方案"""
        if not self.validate_composition(composition):
            raise ValueError("Invalid composition")
        
        svg_parts = [
            '<svg viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg">',
            '<!-- Generated by AtomicRenderer at {} -->'.format(datetime.now())
        ]
        
        for element in composition.get("elements", []):
            svg_element = self.render_element(element)
            svg_parts.append(svg_element)
        
        svg_parts.append('</svg>')
        return '\n'.join(svg_parts)
    
    def render_element(self, element: Dict) -> str:
        """渲染单个元素"""
        element_type = element["type"]
        params = element["params"]
        
        if element_type not in self.SUPPORTED_ELEMENTS:
            raise ValueError(f"Unsupported element type: {element_type}")
        
        renderers = {
            "circle": self.render_circle,
            "ellipse": self.render_ellipse,
            "rectangle": self.render_rectangle,
            "line": self.render_line,
            "arrow": self.render_arrow,
            "text": self.render_text,
            "polygon": self.render_polygon
        }
        
        return renderers[element_type](params)
    
    def render_circle(self, params: Dict) -> str:
        """渲染圆形"""
        cx = self.clamp(params.get("cx", 0), *self.COORDINATE_RANGE["x"])
        cy = self.clamp(params.get("cy", 0), *self.COORDINATE_RANGE["y"])
        r = self.clamp(params.get("r", 10), *self.SIZE_RANGE["radius"])
        fill = self.validate_color(params.get("fill", "#000000"))
        stroke = self.validate_color(params.get("stroke", ""))
        stroke_width = params.get("stroke_width", 0)
        
        attrs = [f'cx="{cx}"', f'cy="{cy}"', f'r="{r}"', f'fill="{fill}"']
        if stroke:
            attrs.append(f'stroke="{stroke}"')
            attrs.append(f'stroke-width="{stroke_width}"')
        
        return f'<circle {" ".join(attrs)}/>'
    
    def render_ellipse(self, params: Dict) -> str:
        """渲染椭圆"""
        cx = self.clamp(params.get("cx", 0), *self.COORDINATE_RANGE["x"])
        cy = self.clamp(params.get("cy", 0), *self.COORDINATE_RANGE["y"])
        rx = self.clamp(params.get("rx", 10), *self.SIZE_RANGE["radius"])
        ry = self.clamp(params.get("ry", 10), *self.SIZE_RANGE["radius"])
        fill = self.validate_color(params.get("fill", "#000000"))
        stroke = self.validate_color(params.get("stroke", ""))
        
        attrs = [f'cx="{cx}"', f'cy="{cy}"', f'rx="{rx}"', f'ry="{ry}"', f'fill="{fill}"']
        if stroke:
            attrs.append(f'stroke="{stroke}"')
        
        return f'<ellipse {" ".join(attrs)}/>'
    
    def render_rectangle(self, params: Dict) -> str:
        """渲染矩形"""
        x = self.clamp(params.get("x", 0), *self.COORDINATE_RANGE["x"])
        y = self.clamp(params.get("y", 0), *self.COORDINATE_RANGE["y"])
        width = self.clamp(params.get("width", 100), *self.SIZE_RANGE["width"])
        height = self.clamp(params.get("height", 100), *self.SIZE_RANGE["height"])
        fill = self.validate_color(params.get("fill", "#000000"))
        rx = params.get("rx", 0)
        
        attrs = [f'x="{x}"', f'y="{y}"', f'width="{width}"', f'height="{height}"', f'fill="{fill}"']
        if rx > 0:
            attrs.append(f'rx="{rx}"')
        
        return f'<rect {" ".join(attrs)}/>'
    
    def render_line(self, params: Dict) -> str:
        """渲染线段"""
        x1 = self.clamp(params.get("x1", 0), *self.COORDINATE_RANGE["x"])
        y1 = self.clamp(params.get("y1", 0), *self.COORDINATE_RANGE["y"])
        x2 = self.clamp(params.get("x2", 0), *self.COORDINATE_RANGE["x"])
        y2 = self.clamp(params.get("y2", 0), *self.COORDINATE_RANGE["y"])
        stroke = self.validate_color(params.get("stroke", "#000000"))
        stroke_width = params.get("stroke_width", 1)
        
        attrs = [f'x1="{x1}"', f'y1="{y1}"', f'x2="{x2}"', f'y2="{y2}"', 
                f'stroke="{stroke}"', f'stroke-width="{stroke_width}"']
        
        return f'<line {" ".join(attrs)}/>'
    
    def render_arrow(self, params: Dict) -> str:
        """渲染箭头"""
        x1 = self.clamp(params.get("x1", 0), *self.COORDINATE_RANGE["x"])
        y1 = self.clamp(params.get("y1", 0), *self.COORDINATE_RANGE["y"])
        x2 = self.clamp(params.get("x2", 0), *self.COORDINATE_RANGE["x"])
        y2 = self.clamp(params.get("y2", 0), *self.COORDINATE_RANGE["y"])
        stroke = self.validate_color(params.get("stroke", "#000000"))
        
        # 计算箭头头部
        angle = math.atan2(y2 - y1, x2 - x1)
        arrow_length = 10
        arrow_angle = math.pi / 6
        
        x3 = x2 - arrow_length * math.cos(angle - arrow_angle)
        y3 = y2 - arrow_length * math.sin(angle - arrow_angle)
        x4 = x2 - arrow_length * math.cos(angle + arrow_angle)
        y4 = y2 - arrow_length * math.sin(angle + arrow_angle)
        
        return f'''<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{stroke}" stroke-width="2"/>
<polygon points="{x2},{y2} {x3},{y3} {x4},{y4}" fill="{stroke}"/>'''
    
    def render_text(self, params: Dict) -> str:
        """渲染文本"""
        x = self.clamp(params.get("x", 0), *self.COORDINATE_RANGE["x"])
        y = self.clamp(params.get("y", 0), *self.COORDINATE_RANGE["y"])
        content = self.sanitize_text(params.get("content", ""))
        font_size = self.clamp(params.get("font_size", 16), 8, 72)
        fill = self.validate_color(params.get("fill", "#000000"))
        text_anchor = params.get("text_anchor", "start")
        
        attrs = [f'x="{x}"', f'y="{y}"', f'font-size="{font_size}"', 
                f'fill="{fill}"', f'text-anchor="{text_anchor}"']
        
        return f'<text {" ".join(attrs)}>{content}</text>'
    
    def render_polygon(self, params: Dict) -> str:
        """渲染多边形"""
        points = params.get("points", [])
        validated_points = []
        
        for point in points:
            if len(point) == 2:
                x = self.clamp(point[0], *self.COORDINATE_RANGE["x"])
                y = self.clamp(point[1], *self.COORDINATE_RANGE["y"])
                validated_points.append(f"{x},{y}")
        
        points_str = " ".join(validated_points)
        fill = self.validate_color(params.get("fill", "#000000"))
        
        return f'<polygon points="{points_str}" fill="{fill}"/>'
    
    # 辅助函数
    def validate_composition(self, composition: Dict) -> bool:
        return "elements" in composition and isinstance(composition["elements"], list)
    
    def validate_color(self, color: str) -> str:
        if not color:
            return "#000000"
        if not self.COLOR_PATTERN.match(color):
            return "#000000"
        return color
    
    def clamp(self, value: float, min_val: float, max_val: float) -> float:
        return max(min_val, min(max_val, value))
    
    def sanitize_text(self, text: str) -> str:
        if len(text) > 200:
            text = text[:200]
        text = text.replace('<', '&lt;').replace('>', '&gt;')
        text = text.replace('&', '&amp;')
        return text


# ============== 第二层：组合决策层（中层）==============

class ComponentComposer:
    """
    组合决策层：将语义图转为渲染方案
    特点：半确定性、LLM辅助、参数验证、自动修正
    """
    
    def __init__(self):
        self.atomic_renderer = AtomicRenderer()
    
    async def compose(self, semantic_graph: Dict, constraints: Dict = None) -> Dict:
        """将语义图转为渲染方案"""
        # 1. 分析语义图
        analysis = self.analyze_semantic_graph(semantic_graph)
        
        # 2. 选择布局策略
        layout_strategy = self.select_layout_strategy(analysis)
        
        # 3. 生成组合方案（使用规则引擎）
        composition = self.generate_with_rules(semantic_graph, layout_strategy)
        
        # 4. 验证和修正
        validated = self.validate_and_correct(composition)
        
        return validated
    
    def analyze_semantic_graph(self, semantic_graph: Dict) -> Dict:
        """分析语义图特征"""
        entities = semantic_graph.get("entities", [])
        relations = semantic_graph.get("relations", [])
        
        analysis = {
            "type": semantic_graph.get("type", "unknown"),
            "entity_count": len(entities),
            "relation_count": len(relations),
            "complexity": "low"
        }
        
        total = analysis["entity_count"] + analysis["relation_count"]
        if total > 20:
            analysis["complexity"] = "high"
        elif total > 10:
            analysis["complexity"] = "medium"
        
        return analysis
    
    def select_layout_strategy(self, analysis: Dict) -> str:
        """选择布局策略"""
        if analysis["type"] == "process":
            return "flow"
        elif analysis["type"] == "structure":
            return "tree"
        elif analysis["type"] == "relationship":
            return "radial"
        else:
            return "grid"
    
    def generate_with_rules(self, semantic_graph: Dict, layout_strategy: str) -> Dict:
        """使用规则引擎生成组合方案"""
        composition = {"elements": []}
        entities = semantic_graph.get("entities", [])
        relations = semantic_graph.get("relations", [])
        
        if layout_strategy == "flow":
            # 从左到右流程布局
            entity_positions = {}
            spacing = 900 / max(len(entities), 1)
            
            for i, entity in enumerate(entities):
                x = 100 + i * spacing
                y = 300
                
                entity_positions[entity["name"]] = (x, y)
                
                # 添加圆形表示实体
                importance = entity.get("importance", 3)
                radius = 30 + importance * 5
                
                composition["elements"].append({
                    "type": "circle",
                    "params": {
                        "cx": x,
                        "cy": y,
                        "r": radius,
                        "fill": self.get_color_by_importance(importance)
                    }
                })
                
                # 添加文本标签
                composition["elements"].append({
                    "type": "text",
                    "params": {
                        "x": x,
                        "y": y + radius + 20,
                        "content": entity["name"],
                        "font_size": 14,
                        "text_anchor": "middle"
                    }
                })
            
            # 添加关系箭头
            for relation in relations:
                from_name = relation["from"]
                to_name = relation["to"]
                
                if from_name in entity_positions and to_name in entity_positions:
                    x1, y1 = entity_positions[from_name]
                    x2, y2 = entity_positions[to_name]
                    
                    # 调整箭头起点和终点（避免与圆形重叠）
                    angle = math.atan2(y2 - y1, x2 - x1)
                    x1 += math.cos(angle) * 50
                    y1 += math.sin(angle) * 50
                    x2 -= math.cos(angle) * 50
                    y2 -= math.sin(angle) * 50
                    
                    composition["elements"].append({
                        "type": "arrow",
                        "params": {
                            "x1": x1,
                            "y1": y1,
                            "x2": x2,
                            "y2": y2,
                            "stroke": "#666666"
                        }
                    })
        
        return composition
    
    def get_color_by_importance(self, importance: int) -> str:
        """根据重要程度选择颜色"""
        colors = {
            5: "#ff9800",  # 橙色（最重要）
            4: "#4caf50",  # 绿色
            3: "#2196f3",  # 蓝色
            2: "#9e9e9e",  # 灰色
            1: "#e0e0e0"   # 浅灰
        }
        return colors.get(importance, "#2196f3")
    
    def validate_and_correct(self, composition: Dict) -> Dict:
        """验证和自动修正组合方案"""
        if "elements" not in composition:
            composition["elements"] = []
        
        validated_elements = []
        
        for element in composition.get("elements", []):
            try:
                if element["type"] not in self.atomic_renderer.SUPPORTED_ELEMENTS:
                    continue
                
                validated_params = self.validate_params(element["type"], element["params"])
                validated_elements.append({
                    "type": element["type"],
                    "params": validated_params
                })
            except Exception as e:
                print(f"Validation error: {e}")
                continue
        
        composition["elements"] = validated_elements
        return composition
    
    def validate_params(self, element_type: str, params: Dict) -> Dict:
        """验证参数"""
        validated = {}
        
        for key, value in params.items():
            if key in ["cx", "cy", "x", "y", "x1", "y1", "x2", "y2"]:
                validated[key] = float(value)
            elif key in ["r", "rx", "ry", "width", "height"]:
                validated[key] = float(value)
            elif key in ["fill", "stroke"]:
                validated[key] = self.atomic_renderer.validate_color(value)
            elif key == "content":
                validated[key] = self.atomic_renderer.sanitize_text(value)
            else:
                validated[key] = value
        
        return validated


# ============== 第三层：语义理解层（顶层）==============

class SemanticAnalyzer:
    """
    语义理解层：理解自然语言，提取语义结构
    特点：LLM驱动、语义提取、抽象描述、平台无关
    """
    
    def __init__(self):
        # 在实际应用中，这里会连接LLM
        pass
    
    async def analyze(self, natural_language: str) -> Dict:
        """分析自然语言，生成语义图"""
        # 模拟LLM的输出（实际应用中会调用LLM API）
        if "光合作用" in natural_language:
            return self.generate_photosynthesis_semantic_graph()
        elif "呼吸" in natural_language:
            return self.generate_respiration_semantic_graph()
        else:
            return self.generate_generic_semantic_graph(natural_language)
    
    def generate_photosynthesis_semantic_graph(self) -> Dict:
        """生成光合作用的语义图"""
        return {
            "type": "process",
            "entities": [
                {"name": "太阳", "type": "能量源", "attributes": ["光能"], "importance": 5},
                {"name": "CO₂", "type": "物质", "attributes": ["碳源"], "importance": 4},
                {"name": "H₂O", "type": "物质", "attributes": ["氢源", "氧源"], "importance": 4},
                {"name": "叶片", "type": "器官", "attributes": ["叶绿体", "气孔"], "importance": 5},
                {"name": "O₂", "type": "产物", "attributes": ["氧气"], "importance": 3},
                {"name": "葡萄糖", "type": "产物", "attributes": ["有机物"], "importance": 5}
            ],
            "relations": [
                {"from": "太阳", "to": "叶片", "relation": "input", "label": "光能"},
                {"from": "CO₂", "to": "叶片", "relation": "input", "label": "通过气孔"},
                {"from": "H₂O", "to": "叶片", "relation": "input", "label": "根部吸收"},
                {"from": "叶片", "to": "O₂", "relation": "output", "label": "释放"},
                {"from": "叶片", "to": "葡萄糖", "relation": "output", "label": "生成"}
            ],
            "process": [
                {"step": 1, "action": "光能吸收", "objects": ["叶绿素"], "result": "能量捕获"},
                {"step": 2, "action": "水分解", "objects": ["H₂O"], "result": "释放O₂和H"},
                {"step": 3, "action": "CO₂固定", "objects": ["CO₂"], "result": "碳原子进入"},
                {"step": 4, "action": "糖合成", "objects": ["碳原子", "H"], "result": "生成葡萄糖"}
            ]
        }
    
    def generate_respiration_semantic_graph(self) -> Dict:
        """生成呼吸作用的语义图"""
        return {
            "type": "process",
            "entities": [
                {"name": "葡萄糖", "type": "反应物", "importance": 5},
                {"name": "O₂", "type": "反应物", "importance": 4},
                {"name": "线粒体", "type": "细胞器", "importance": 5},
                {"name": "CO₂", "type": "产物", "importance": 3},
                {"name": "H₂O", "type": "产物", "importance": 3},
                {"name": "能量", "type": "产物", "importance": 5}
            ],
            "relations": [
                {"from": "葡萄糖", "to": "线粒体", "relation": "input"},
                {"from": "O₂", "to": "线粒体", "relation": "input"},
                {"from": "线粒体", "to": "CO₂", "relation": "output"},
                {"from": "线粒体", "to": "H₂O", "relation": "output"},
                {"from": "线粒体", "to": "能量", "relation": "output"}
            ]
        }
    
    def generate_generic_semantic_graph(self, text: str) -> Dict:
        """生成通用语义图"""
        return {
            "type": "unknown",
            "entities": [],
            "relations": [],
            "process": []
        }


# ============== 完整系统整合 ==============

class LayeredVisualizationSystem:
    """
    分层可视化系统：三层协同工作
    """
    
    def __init__(self):
        self.semantic_analyzer = SemanticAnalyzer()
        self.composer = ComponentComposer()
        self.renderer = AtomicRenderer()
    
    async def visualize(self, natural_language: str) -> str:
        """
        完整流程：自然语言 → SVG
        
        步骤：
        1. 顶层：语义理解
        2. 中层：组合决策
        3. 底层：原子渲染
        """
        print("=" * 60)
        print("🌱 分层抽象可视化系统")
        print("=" * 60)
        
        # 第一层：语义理解
        print("\n【第一层：语义理解】")
        print(f"输入：{natural_language}")
        semantic_graph = await self.semantic_analyzer.analyze(natural_language)
        print(f"语义图类型：{semantic_graph['type']}")
        print(f"实体数量：{len(semantic_graph['entities'])}")
        print(f"关系数量：{len(semantic_graph['relations'])}")
        
        # 第二层：组合决策
        print("\n【第二层：组合决策】")
        composition = await self.composer.compose(semantic_graph)
        print(f"元素数量：{len(composition['elements'])}")
        
        # 第三层：原子渲染
        print("\n【第三层：原子渲染】")
        svg = self.renderer.render(composition)
        print(f"SVG大小：{len(svg)} 字节")
        
        print("\n" + "=" * 60)
        print("✅ 可视化生成完成！")
        print("=" * 60)
        
        return svg


# ============== 演示 ==============

async def demo():
    """演示完整流程"""
    system = LayeredVisualizationSystem()
    
    # 示例1：光合作用
    print("\n\n")
    svg = await system.visualize("请展示光合作用的过程")
    
    # 保存SVG
    with open("/Users/zhaoyang/iFlow/aiteacher-2/layered_output.svg", "w", encoding="utf-8") as f:
        f.write(svg)
    
    print("\n📄 SVG已保存到：layered_output.svg")
    print("\n前500字符预览：")
    print(svg[:500] + "...")


if __name__ == "__main__":
    asyncio.run(demo())
